-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  description text,
  rating CHAR(1)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Google', 'http://www.google.com', 'Internet-related services and products.', '3'),
  ('Thinkful', 'http://www.thinkful.com', '1-on-1 learning to accelerate your way to a new high-growth tech career!', '5'),
  ('Github', 'http://www.github.com', 'brings together the largest community of developers.', '4'),
  ('DBeaver', 'https://dbeaver.io/', 'Free Universal Database Tool', '3'),
  ('repl.it', 'https://repl.it/', 'Code, create, and learn together', '3'),
  ('coolers', 'https://coolors.co/', 'Create a palette', '3'),
  ('imagecolorpicker', 'https://imagecolorpicker.com/en/', 'Click on the image to get the html codes.', '3'),
  ('Nu Html Checker', 'https://validator.w3.org/nu/', 'This tool is an ongoing experiment in better HTML checking', '3'),
  ('Flexbox Defense', 'http://www.flexboxdefense.com/', 'Practice CSS with this tower defense game', '3'),
  ('Formspree', 'https://formspree.io/', 'Custom forms with no server code', '3');